### ISSUE TITLE
Future.Speckle Needs A New Name

### ISSUE THREAD

**Issue by didimitrie** [didimitrie/future.speckle#12]
Suggestions welcome :+1:

**Comment by bigdoods** [comment]
speckle is growing on me;)

**Comment by didimitrie** [comment]
Yes, on me too. And everyone's saying to keep it :+1: 
Will keep this open, who knows :dancers:

**Comment by alexykot** [comment]
Don't see why would you need to change it. I think it's good as it is.

**Comment by didimitrie** [comment]
Right, public sentiment has voted (both directly here and in real-life interactions)
