### ISSUE TITLE
I can't connect to my mongoDB on my CentOS Server.

### ISSUE THREAD

**Issue by bucky0970** [didimitrie/future.speckle#57]
Where is the error? (check multiple if it applies) 
- [ ] Backend (uploading models, logging in, etc.)
- [ ] Frontend (the viewer). If so, please specify on which interface (default, comparison, etc)
- [ ] Rhino Grasshopper Exporter.
- [V] Running a local instance. If so, please specify on which OS. 

####What were you trying to do?
I launch a local speckle site on my Mac, it's work. But when I upload to my CentOS Server, it just hang over somewhere, no error, no success. And I found it's relate to my mongoDB, I can't link successfully.
####What is the expected behaviour? 
Because it can't link to DB, so when I log in, the node will sleep, can't into profile page.
####What did actually happen?
I create a test.js

`var mongoose = require('mongoose');
[redacted]
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function callback () {
  console.log("h");
});`

If link successful,it's will show "h", when I run this js file in different directory, it's work. And I copy it to speckle directory, it hangs. I don't know why....please help me.

**Comment by didimitrie** [comment]
sorry for the belated reply, but i guess this is a mongoose issue on your side (mongoose on centos, or mlab refusing that connection)? this worked fine on ubuntu and osx...

and please don't post your passwds in here! I've redacted your comment :)

**Comment by bucky0970** [comment]
Sorry, I did not notice the passwd~ Thanks for reply.
